[build-system]
requires = [
    "setuptools>=65.5.1",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tools.yapf]
based_on_style = "pep8"
indent_width = 2 

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = false
combine_as_imports = true