services:
  es:
    image: europe-west2-docker.pkg.dev/ons-ci-aims/aims-api-demo/elasticsearch-aims-8.15.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster-ai
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "path.repo=/usr/share/elasticsearch/data/snapshots"
    ports:
      - "9200:9200"
      - "9300:9300"
  cerebro:
    image: "lmenezes/cerebro"
    ports:
      - "1234:9000"
    depends_on:
      - es
#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:8.15.3
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - es
  address-index-api:
    image: "europe-west2-docker.pkg.dev/ons-ci-aims/aims-api-demo/address-index-server:1.3.2"
    ports:
      - "9001:9000"
    depends_on:
      - es
    environment:
      - ONS_AI_API_ES_CLUSTER_NAME=docker-cluster-ai
      - ONS_AI_API_ES_URI=es
      - ONS_AI_API_ES_PORT=9200
      - ONS_AI_API_MIN_PARTIAL_SIZE=2
      - ONS_AI_API_VALID_EPOCHS=111        
  address-index-ui:
    image: "europe-west2-docker.pkg.dev/ons-ci-aims/aims-api-demo/address-index-ui:1.3.28"
    ports:
      - "5000:5000"
    depends_on:
      - address-index-api
    environment:
      - API_URL=http://host.docker.internal:9001
      - BM_API_URL=http://host.docker.internal:9001
      - PROJECT_DOMAIN=http://localhost:9001
      - FLASK_ENV=production
      - FLASK_APP=aims_ui
      - API_AUTH_TYPE=JWT
      - JWT_TOKEN=abc123
      - SECRET_KEY=secret