"""FLASK BASE CONFIG"""
import os

JSONIFY_PRETTYPRINT_REGULAR = True
MAX_CONTENT_LENGTH = 3 * 1000 * 1000
API_AUTH_TYPE = os.getenv('API_AUTH_TYPE')
JWT_TOKEN = os.getenv('JWT_TOKEN')

API_BSC_AUTH_USERNAME = os.getenv('API_BSC_AUTH_USERNAME')
API_BSC_AUTH_PASSWORD = os.getenv('API_BSC_AUTH_PASSWORD')
