
import pytest

from aims_ui.page_helpers.classification_utilities import check_reverse_classification

classification_pairs = [
    {'Commercial': 'C*'},
    {'Agricultural': 'CA*'},
    {'Farm / Non-Residential Associated Building': 'CA01*'},
    {'Fishery': 'CA02*'},
    {'Fish Farming': 'CA02FF*'},
    {'Fish Hatchery': 'CA02FH*'},
    {'Fish Processing': 'CA02FP*'},
    {'Oyster / Mussel Bed': 'CA02OY*'},
    {'Horticulture': 'CA03*'},
    {'Smallholding': 'CA03SH*'},
    {'Vineyard': 'CA03VY*'},
    {'Watercress Bed': 'CA03WB*'},
    {'Slaughter House / Abattoir': 'CA04*'},
    {'Community Services': 'CC*'},
    {'Law Court': 'CC02*'},
    {'Prison': 'CC03*'},
    {'HM Detention Centre': 'CC03HD*'},
    {'HM Prison Service': 'CC03PR*'},
    {'Secure Residential Accommodation': 'CC03SC*'},
    {'Public / Village Hall / Other Community Facility': 'CC04*'},
    {'Youth Recreational / Social Club': 'CC04YR*'},
    {'Public Convenience': 'CC05*'},
    {'Cemetery / Crematorium / Graveyard. In Current Use.': 'CC06*'},
    {'Columbarium': 'CC06CB*'},
    {'Chapel Of Rest': 'CC06CR*'},
    {'Crematorium': 'CC06CN*'},
    {'Cemetery': 'CC06CY*'},
    {'Military Cemetery': 'CC06MC*'},
    {'Mortuary': 'CC06MY*'},
    {'Church Hall / Religious Meeting Place / Hall': 'CC07*'},
    {'Community Service Centre / Office': 'CC08*'},
    {'Public Household Waste Recycling Centre (HWRC)': 'CC09*'},
    {'Recycling Site': 'CC10*'},
    {'CCTV': 'CC11*'},
    {'Job Centre': 'CC12*'},
    {'Education': 'CE*'},
    {'College': 'CE01*'},
    {'Further Education': 'CE01FE*'},
    {'Higher Education': 'CE01HE*'},
    {"Children''s Nursery / Crèche": 'CE02*'},
    {'Preparatory / First / Primary / Infant / Junior / Middle School': 'CE03*'},
    {'First School': 'CE03FS*'},
    {'Infant School': 'CE03IS*'},
    {'Junior School': 'CE03JS*'},
    {'Middle School': 'CE03MS*'},
    {'Non State Primary / Preparatory School': 'CE03NP*'},
    {'Primary School': 'CE03PS*'},
    {'Secondary / High School': 'CE04*'},
    {'Non State Secondary School': 'CE04NS*'},
    {'Secondary School': 'CE04SS*'},
    {'University': 'CE05*'},
    {'Special Needs Establishment.': 'CE06*'},
    {'Other Educational Establishment': 'CE07*'},
    {'Hotel / Motel / Boarding / Guest House': 'CH*'},
    {'Boarding / Guest House / Bed And Breakfast / Youth Hostel': 'CH01*'},
    {'Youth Hostel': 'CH01YH*'},
    {'Holiday Let/Accomodation/Short-Term Let Other Than CH01': 'CH02*'},
    {'Hotel/Motel': 'CH03*'},
    {'Industrial Applicable to manufacturing, engineering, maintenance, storage / wholesale distribution and extraction sites': 'CI*'},
    {'Factory/Manufacturing': 'CI01*'},
    {'Aircraft Works': 'CI01AW*'},
    {'Boat Building': 'CI01BB*'},
    {'Brick Works': 'CI01BR*'},
    {'Brewery': 'CI01BW*'},
    {'Cider Manufacture': 'CI01CD*'},
    {'Chemical Works': 'CI01CM*'},
    {'Cement Works': 'CI01CW*'},
    {'Dairy Processing': 'CI01DA*'},
    {'Distillery': 'CI01DY*'},
    {'Flour Mill': 'CI01FL*'},
    {'Food Processing': 'CI01FO*'},
    {'Glassworks': 'CI01GW*'},
    {'Manufacturing': 'CI01MG*'},
    {'Oast House': 'CI01OH*'},
    {'Oil Refining': 'CI01OR*'},
    {'Pottery Manufacturing': 'CI01PG*'},
    {'Paper Mill': 'CI01PM*'},
    {'Printing Works': 'CI01PW*'},
    {'Shipyard': 'CI01YD*'},
    {'Sugar Refinery': 'CI01SR*'},
    {'Steel Works': 'CI01SW*'},
    {'Timber Mill': 'CI01TL*'},
    {'Winery': 'CI01WN*'},
    {'Mineral / Ore Working / Quarry / Mine': 'CI02*'},
    {'Mineral Mining / Active': 'CI02MA*'},
    {'Mineral Distribution / Storage': 'CI02MD*'},
    {'Mineral Processing': 'CI02MP*'},
    {'Oil / Gas Extraction / Active': 'CI02OA*'},
    {'Mineral Quarrying / Open Extraction / Active': 'CI02QA*'},
    {'Workshop / Light Industrial': 'CI03*'},
    {'Servicing Garage': 'CI03GA*'},
    {'Warehouse / Store / Storage Depot': 'CI04*'},
    {'Crop Handling / Storage': 'CI04CS*'},
    {'Postal Sorting / Distribution': 'CI04PL*'},
    {'Solid Fuel Storage': 'CI04SO*'},
    {'Timber Storage': 'CI04TS*'},
    {'Wholesale Distribution': 'CI05*'},
    {'Solid Fuel Distribution': 'CI05SF*'},
    {'Timber Distribution': 'CI05TD*'},
    {'Recycling Plant': 'CI06*'},
    {'Incinerator / Waste Transfer Station': 'CI07*'},
    {'Maintenance Depot': 'CI08*'},
    {'Leisure - Applicable to recreational sites and enterprises': 'CL*'},
    {'Amusements': 'CL01*'},
    {'Leisure Pier': 'CL01LP*'},
    {'Holiday / Campsite': 'CL02*'},
    {'Camping': 'CL02CG*'},
    {'Caravanning': 'CL02CV*'},
    {'Holiday Accommodation': 'CL02HA*'},
    {'Holiday Centre': 'CL02HO*'},
    {'Youth Organisation Camp': 'CL02YC*'},
    {'Library': 'CL03*'},
    {'Reading Room': 'CL03RR*'},
    {'Museum / Gallery': 'CL04*'},
    {'Art Centre / Gallery': 'CL04AC*'},
    {'Aviation Museum': 'CL04AM*'},
    {'Heritage Centre': 'CL04HG*'},
    {'Industrial Museum': 'CL04IM*'},
    {'Military Museum': 'CL04MM*'},
    {'Science Museum': 'CL04SM*'},
    {'Transport Museum': 'CL04TM*'},
    {'Maritime Museum': 'CL04NM*'},
    {'Indoor / Outdoor Leisure / Sporting Activity / Centre': 'CL06*'},
    {'Athletics Facility': 'CL06AH*'},
    {'Bowls Facility': 'CL06BF*'},
    {'Cricket Facility': 'CL06CK*'},
    {'Curling Facility': 'CL06CU*'},
    {'Cycling Sports Facility': 'CL06YF*'},
    {'Diving / Swimming Facility': 'CL06DS*'},
    {'Equestrian Sports Facility': 'CL06EQ*'},
    {'Football Facility': 'CL06FB*'},
    {'Fishing / Angling Facility': 'CL06FI*'},
    {'Golf Facility': 'CL06GF*'},
    {'Gliding Facility': 'CL06GL*'},
    {'Greyhound Racing Facility': 'CL06GR*'},
    {'Hockey Facility': 'CL06HF*'},
    {'Horse Racing Facility': 'CL06HR*'},
    {'Historic Vessel / Aircraft / Vehicle': 'CL06HV*'},
    {'Activity / Leisure / Sports Centre': 'CL06LS*'},
    {'Model Sports Facility': 'CL06ME*'},
    {'Motor Sports Facility': 'CL06MF*'},
    {'Playing Field': 'CL06PF*'},
    {'Racquet Sports Facility': 'CL06QS*'},
    {'Rugby Facility': 'CL06RF*'},
    {'Recreation Ground': 'CL06RG*'},
    {'Shinty Facility': 'CL06SI*'},
    {'Skateboarding Facility': 'CL06SK*'},
    {'Civilian Firing Facility': 'CL06SX*'},
    {'Tenpin Bowling Facility': 'CL06TB*'},
    {'Public Tennis Court': 'CL06TN*'},
    {'Water Sports Facility': 'CL06WA*'},
    {'Winter Sports Facility': 'CL06WP*'},
    {'Wildlife Sports Facility': 'CL06WY*'},
    {'Bingo Hall / Cinema / Conference / Exhibition Centre / Theatre / Concert Hall': 'CL07*'},
    {'Theatre': 'CL07TH*'},
    {'Cinema': 'CL07CI*'},
    {'Entertainment Complex': 'CL07EN*'},
    {'Conference / Exhibition Centre': 'CL07EX*'},
    {'Zoo / Theme Park': 'CL08*'},
    {'Amusement Park': 'CL08AK*'},
    {'Model Village Site': 'CL08MX*'},
    {'Wildlife / Zoological Park': 'CL08WZ*'},
    {'Aquatic Attraction': 'CL08AQ*'},
    {'Beach Hut (Recreational, Non-Residential Use Only)': 'CL09*'},
    {'Licensed Private Members Club': 'CL10*'},
    {'Recreational / Social Club': 'CL10RE*'},
    {'Arena / Stadium': 'CL11*'},
    {'Stadium': 'CL11SD*'},
    {'Showground': 'CL11SJ*'},
    {'Medical': 'CM*'},
    {'Dentist': 'CM01*'},
    {'General Practice Surgery / Clinic': 'CM02*'},
    {'Health Care Services': 'CM02HL*'},
    {'Health Centre': 'CM02HC*'},
    {'Hospital / Hospice': 'CM03*'},
    {'Hospice': 'CM03HI*'},
    {'Hospital': 'CM03HP*'},
    {'Medical / Testing / Research Laboratory': 'CM04*'},
    {'Professional Medical Service': 'CM05*'},
    {'Assessment / Development Services': 'CM05ZS*'},
    {'Animal Centre': 'CN*'},
    {'Cattery / Kennel': 'CN01*'},
    {'Animal Services': 'CN02*'},
    {'Animal Quarantining': 'CN02AX*'},
    {'Equestrian': 'CN03*'},
    {'Horse Racing / Breeding Stable': 'CN03HB*'},
    {'Commercial Stabling / Riding': 'CN03SB*'},
    {'Vet / Animal Medical Treatment': 'CN04*'},
    {'Animal / Bird / Marine Sanctuary': 'CN05*'},
    {'Animal Sanctuary': 'CN05AN*'},
    {'Marine Sanctuary': 'CN05MR*'},
    {'Office': 'CO*'},
    {'Office / Work Studio': 'CO01*'},
    {'Embassy / High Commission / Consulate': 'CO01EM*'},
    {'Film Studio': 'CO01FM*'},
    {'Central Government Service': 'CO01GV*'},
    {'Local Government Service': 'CO01LG*'},
    {'Broadcasting (TV / Radio)': 'CO02*'},
    {'Retail': 'CR*'},
    {'Bank / Financial Service': 'CR01*'},
    {'Retail Service Agent': 'CR02*'},
    {'Post Office': 'CR02PO*'},
    {'Market (Indoor / Outdoor)': 'CR04*'},
    {'Fish Market': 'CR04FK*'},
    {'Fruit / Vegetable Market': 'CR04FV*'},
    {'Livestock Market': 'CR04LV*'},
    {'Petrol Filling Station': 'CR05*'},
    {'Public House / Bar / Nightclub': 'CR06*'},
    {'Restaurant / Cafeteria': 'CR07*'},
    {'Shop / Showroom': 'CR08*'},
    {'Garden Centre': 'CR08GC*'},
    {'Other Licensed Premise / Vendor': 'CR09*'},
    {'Fast Food Outlet / Takeaway (Hot / Cold)': 'CR10*'},
    {'Automated Teller Machine (ATM)': 'CR11*'},
    {'Storage Land': 'CS*'},
    {'General Storage Land': 'CS01*'},
    {'Builders Yard': 'CS02*'},
    {'Transport': 'CT*'},
    {'Airfield / Airstrip / Airport / Air Transport Infrastructure Facility': 'CT01*'},
    {'Airfield': 'CT01AF*'},
    {'Air Passenger Terminal': 'CT01AY*'},
    {'Air Transport Infrastructure Services': 'CT01AI*'},
    {'Airport': 'CT01AP*'},
    {'Helicopter Station': 'CT01HS*'},
    {'Heliport / Helipad': 'CT01HT*'},
    {'Bus Shelter': 'CT02*'},
    {'Car / Coach / Commercial Vehicle / Taxi Parking / Park And Ride Site': 'CT03*'},
    {'Public Park And Ride': 'CT03PK*'},
    {'Public Car Parking': 'CT03PP*'},
    {'Public Coach Parking': 'CT03PU*'},
    {'Public Commercial Vehicle Parking': 'CT03VP*'},
    {'Goods Freight Handling / Terminal': 'CT04*'},
    {'Air Freight Terminal': 'CT04AE*'},
    {'Container Freight': 'CT04CF*'},
    {'Road Freight Transport': 'CT04RH*'},
    {'Rail Freight Transport': 'CT04RT*'},
    {'Marina': 'CT05*'},
    {'Mooring': 'CT06*'},
    {'Railway Asset': 'CT07*'},
    {'Station / Interchange / Terminal / Halt': 'CT08*'},
    {'Bus / Coach Station': 'CT08BC*'},
    {'Railway Station': 'CT08RS*'},
    {'Vehicular Rail Terminal': 'CT08VH*'},
    {'Transport Track / Way': 'CT09*'},
    {'Cliff Railway': 'CT09CL*'},
    {'Chair Lift / Cable Car / Ski Tow': 'CT09CX*'},
    {'Monorail': 'CT09MO*'},
    {'Vehicle Storage': 'CT10*'},
    {'Boat Storage': 'CT10BG*'},
    {'Bus / Coach Depot': 'CT10BU*'},
    {'Transport Related Infrastructure': 'CT11*'},
    {'Aqueduct': 'CT11AD*'},
    {'Lock': 'CT11LK*'},
    {'Weir': 'CT11WE*'},
    {'Weighbridge / Load Gauge': 'CT11WG*'},
    {'Overnight Lorry Park': 'CT12*'},
    {'Harbour / Port / Dock / Dockyard / Slipway / Landing Stage / Pier / Jetty / Pontoon / Terminal / Berthing / Quay': 'CT13*'},
    {'Passenger Ferry Terminal': 'CT13FR*'},
    {'Non-Tanker Nautical Berthing': 'CT13NB*'},
    {'Nautical Refuelling Facility': 'CT13NF*'},
    {'Slipway': 'CT13SA*'},
    {'Ship Passenger Terminal': 'CT13SP*'},
    {'Tanker Berthing': 'CT13TK*'},
    {'Vehicular Ferry Terminal': 'CT13VF*'},
    {'Utility': 'CU*'},
    {'Electricity Sub-Station': 'CU01*'},
    {'Landfill': 'CU02*'},
    {'Power Station / Energy Production': 'CU03*'},
    {'Electricity Distribution Facility': 'CU03ED*'},
    {'Electricity Production Facility': 'CU03EP*'},
    {'Wind Farm': 'CU03WF*'},
    {'Wind Turbine': 'CU03WU*'},
    {'Pump House / Pumping Station / Water Tower': 'CU04*'},
    {'Water Controlling / Pumping': 'CU04WC*'},
    {'Water Distribution / Pumping': 'CU04WD*'},
    {'Water Quality Monitoring': 'CU04WM*'},
    {'Water Storage': 'CU04WS*'},
    {'Waste Water Distribution / Pumping': 'CU04WW*'},
    {'Telecommunication': 'CU06*'},
    {'Telecommunications Mast': 'CU06TE*'},
    {'Telephone Exchange': 'CU06TX*'},
    {'Water / Waste Water / Sewage Treatment Works': 'CU07*'},
    {'Waste Water Treatment': 'CU07WR*'},
    {'Water Treatment': 'CU07WT*'},
    {'Gas / Oil Storage / Distribution': 'CU08*'},
    {'Gas Governor': 'CU08GG*'},
    {'Gas Holder': 'CU08GH*'},
    {'Oil Terminal': 'CU08OT*'},
    {'Other Utility Use': 'CU09*'},
    {'Observatory': 'CU09OV*'},
    {'Radar Station': 'CU09RA*'},
    {'Satellite Earth Station': 'CU09SE*'},
    {'Cable Terminal Station': 'CU09CQ*'},
    {'Waste Management': 'CU10*'},
    {'Telephone Box': 'CU11*'},
    {'Other Public Telephones': 'CU11OP*'},
    {'Dam': 'CU12*'},
    {'Emergency / Rescue Service': 'CX*'},
    {'Police / Transport Police / Station': 'CX01*'},
    {'Police Training': 'CX01PT*'},
    {'Fire Station': 'CX02*'},
    {'Fire Service Training': 'CX02FT*'},
    {'Ambulance Station': 'CX03*'},
    {'Air Sea Rescue / Air Ambulance': 'CX03AA*'},
    {'Lifeboat Services / Station': 'CX04*'},
    {'Coastguard Rescue / Lookout / Station': 'CX05*'},
    {'Mountain Rescue Station': 'CX06*'},
    {'Lighthouse': 'CX07*'},
    {'Police Box / Kiosk': 'CX08*'},
    {'Information': 'CZ*'},
    {'Advertising Hoarding': 'CZ01*'},
    {'Tourist Information Signage': 'CZ02*'},
    {'Visitor Information': 'CZ02VI*'},
    {'Traffic Information Signage': 'CZ03*'},
    {'Land': 'L*'},
    {'Agricultural - Applicable to land in farm ownership and not run as a separate business enterprise': 'LA*'},
    {'Grazing Land': 'LA01*'},
    {'Permanent Crop / Crop Rotation': 'LA02*'},
    {'Orchard': 'LA02OC*'},
    {'Aviary / Dovecot / Cage': 'LB99AV*'},
    {'Bandstand': 'LB99BD*'},
    {'Pavilion / Changing Room': 'LB99PI*'},
    {'Sports Viewing Structure': 'LB99SV*'},
    {'Burial Ground': 'LC*'},
    {'Historic / Disused Cemetery / Graveyard': 'LC01*'},
    {'Development': 'LD*'},
    {'Development Site': 'LD01*'},
    {'Commercial Construction Site': 'LD01CC*'},
    {'Community Construction Site': 'LD01CO*'},
    {'Residential Construction Site': 'LD01RN*'},
    {'Transport Construction Site': 'LD01TC*'},
    {'Forestry': 'LF*'},
    {'Forest / Arboretum / Pinetum (Managed / Unmanaged)': 'LF02*'},
    {'Arboretum': 'LF02AU*'},
    {'Woodland': 'LF03*'},
    {'Allotment': 'LL*'},
    {'Amenity - Open areas not attracting visitors': 'LM*'},
    {'Landscaped Roundabout': 'LM01*'},
    {'Verge / Central Reservation': 'LM02*'},
    {'Natural Central Reservation': 'LM02NV*'},
    {'Natural Verge': 'LM02VE*'},
    {'Maintained Amenity Land': 'LM03*'},
    {'Maintained Surfaced Area': 'LM04*'},
    {'Made Central Reservation': 'LM04MV*'},
    {'Pavement': 'LM04PV*'},
    {'Open Space': 'LO*'},
    {'Heath / Moorland': 'LO01*'},
    {'Park': 'LP*'},
    {'Public Park / Garden': 'LP01*'},
    {'Public Open Space / Nature Reserve': 'LP02*'},
    {'Playground': 'LP03*'},
    {'Play Area': 'LP03PA*'},
    {'Paddling Pool': 'LP03PD*'},
    {'Private Park / Garden': 'LP04*'},
    {'Unused Land': 'LU*'},
    {'Vacant / Derelict Land': 'LU01*'},
    {'Water': 'LW*'},
    {'Lake / Reservoir': 'LW01*'},
    {'Balancing Pond': 'LW01BP*'},
    {'Buried Reservoir': 'LW01BV*'},
    {'Named Pond': 'LW02*'},
    {'Dew Pond': 'LW02DE*'},
    {'Decoy Pond': 'LW02DP*'},
    {'Static Water': 'LW02IW*'},
    {'Waterway': 'LW03*'},
    {'Leats / Races': 'LW03LR*'},
    {'Drain': 'LW03DR*'},
    {'Military': 'M*'},
    {'Army': 'MA*'},
    {'Army Military Range': 'MA99AR*'},
    {'Army Site': 'MA99AS*'},
    {'Army Military Training': 'MA99AT*'},
    {'Army Military Storage': 'MA99AG*'},
    {'Military Target': 'MB99TG*'},
    {'Air Force': 'MF*'},
    {'Air Force Military Storage': 'MF99UG*'},
    {'Air Force Military Range': 'MF99UR*'},
    {'Air Force Site': 'MF99US*'},
    {'Air Force Military Training': 'MF99UT*'},
    {'Defence Estates': 'MG*'},
    {'Navy': 'MN*'},
    {'Naval Military Storage': 'MN99VG*'},
    {'Naval Military Range': 'MN99VR*'},
    {'Naval Site': 'MN99VS*'},
    {'Naval Military Training': 'MN99VT*'},
    {'Other (Ordnance Survey Only)': 'O*'},
    {'Aid To Navigation': 'OA*'},
    {'Aid To Aeronautical Navigation': 'OA01*'},
    {'Aeronautical Navigation Beacon / Light': 'OA01AL*'},
    {'Landing Light': 'OA01LL*'},
    {'Signal Square': 'OA01SQ*'},
    {'Wind Sock / Wind Tee': 'OA01WK*'},
    {'Aid To Nautical Navigation': 'OA02*'},
    {'Daymark': 'OA02DM*'},
    {'Fog Horn Warning': 'OA02FG*'},
    {'Nautical Navigation Beacon / Light': 'OA02NL*'},
    {'Aid To Road Navigation': 'OA03*'},
    {'Guide Post': 'OA03GP*'},
    {'Coastal Protection / Flood Prevention': 'OC*'},
    {'Boulder Wall / Sea Wall': 'OC01*'},
    {'Flood Gate / Flood Sluice Gate / Flood Valve': 'OC02*'},
    {'Groyne': 'OC03*'},
    {'Rip-Rap': 'OC04*'},
    {'Emergency Support': 'OE*'},
    {'Beach Office / First Aid Facility': 'OE01*'},
    {'Emergency Telephone (Non Motorway)': 'OE02*'},
    {'Fire Alarm Structure / Fire Observation Tower / Fire Beater Facility': 'OE03*'},
    {'Emergency Equipment Point / Emergency Siren / Warning Flag': 'OE04*'},
    {'Lifeguard Facility': 'OE05*'},
    {'Life / Belt / Buoy / Float / Jacket / Safety Rope': 'OE06*'},
    {'Street Furniture': 'OF*'},
    {'Agricultural Support Objects': 'OG*'},
    {'Fish Ladder / Lock / Pen / Trap': 'OG01*'},
    {'Livestock Pen / Dip': 'OG02*'},
    {'Currick': 'OG03*'},
    {'Slurry Bed / Pit': 'OG04*'},
    {'Historical Site / Object': 'OH*'},
    {'Historic Structure / Object': 'OH01*'},
    {'Industrial Support': 'OI*'},
    {'Adit / Incline / Level': 'OI01*'},
    {'Caisson / Dry Dock / Grid': 'OI02*'},
    {'Channel / Conveyor / Conduit / Pipe': 'OI03*'},
    {'Chimney / Flue': 'OI04*'},
    {'Crane / Hoist / Winch / Material Elevator': 'OI05*'},
    {'Flare Stack': 'OI06*'},
    {'Hopper / Silo / Cistern / Tank': 'OI07*'},
    {'Grab / Skip / Other Industrial Waste Machinery / Discharging': 'OI08*'},
    {'Kiln / Oven / Smelter': 'OI09*'},
    {'Manhole / Shaft': 'OI10*'},
    {'Industrial Overflow / Sluice / Valve / Valve Housing': 'OI11*'},
    {'Cooling Tower': 'OI12*'},
    {'Solar Panel / Waterwheel': 'OI13*'},
    {'Telephone Pole / Post': 'OI14*'},
    {'Electricity Distribution Pole / Pylon': 'OI15*'},
    {'Significant Natural Object': 'ON*'},
    {'Boundary / Significant / Historic Tree / Pollard': 'ON01*'},
    {'Boundary / Significant Rock / Boulder': 'ON02*'},
    {'Natural Hole (Blow / Shake / Swallow)': 'ON03*'},
    {'Ornamental / Cultural Object': 'OO*'},
    {'Mausoleum / Tomb / Grave': 'OO02*'},
    {'Simple Ornamental Object': 'OO03*'},
    {'Maze': 'OO04*'},
    {'Sport / Leisure Support': 'OP*'},
    {'Butt / Hide': 'OP01*'},
    {'Gallop / Ride': 'OP02*'},
    {'Miniature Railway': 'OP03*'},
    {'Royal Mail Infrastructure': 'OR*'},
    {'Postal Box': 'OR01*'},
    {'Postal Delivery Box / Pouch': 'OR02*'},
    {'PO Box': 'OR03*'},
    {'Additional Mail / Packet Addressee': 'OR04*'},
    {'Scientific / Observation Support': 'OS*'},
    {'Meteorological Station / Equipment': 'OS01*'},
    {'Radar / Satellite Infrastructure': 'OS02*'},
    {'Telescope / Observation Infrastructure / Astronomy': 'OS03*'},
    {'Transport Support': 'OT*'},
    {'Cattle Grid / Ford': 'OT01*'},
    {'Elevator / Escalator / Steps': 'OT02*'},
    {'Footbridge / Walkway': 'OT03*'},
    {'Pole / Post / Bollard (Restricting Vehicular Access)': 'OT04*'},
    {'Subway / Underpass': 'OT05*'},
    {'Customs Inspection Facility': 'OT06*'},
    {'Lay-By': 'OT07*'},
    {'Level Crossing': 'OT08*'},
    {'Mail Pick Up': 'OT09*'},
    {'Railway Pedestrian Crossing': 'OT10*'},
    {'Railway Buffer': 'OT11*'},
    {'Rail Drag': 'OT12*'},
    {'Rail Infrastructure Services': 'OT13*'},
    {'Rail Kilometre Distance Marker': 'OT14*'},
    {'Railway Lighting': 'OT15*'},
    {'Rail Mile Distance Marker': 'OT16*'},
    {'Railway Turntable': 'OT17*'},
    {'Rail Weighbridge': 'OT18*'},
    {'Rail Signalling': 'OT19*'},
    {'Railway Traverse': 'OT20*'},
    {'Goods Tramway': 'OT21*'},
    {'Road Drag': 'OT22*'},
    {'Vehicle Dip': 'OT23*'},
    {'Road Turntable': 'OT24*'},
    {'Road Mile Distance Marker': 'OT25*'},
    {'Road Kilometre Distance Marker': 'OT26*'},
    {'Road Infrastructure Services': 'OT27*'},
    {'Unsupported Site': 'OU*'},
    {'Cycle Parking Facility': 'OU01*'},
    {'Picnic / Barbeque Site': 'OU04*'},
    {'Travelling Persons Site': 'OU05*'},
    {'Shelter (Not Including Bus Shelter)': 'OU08*'},
    {'Parent Shell': 'P*'},
    {'Property Shell': 'PP*'},
    {'Street Record': 'PS*'},
    {'Residential': 'R*'},
    {'Car Park Space': 'RC*'},
    {'Allocated Parking': 'RC01*'},
    {'Dwelling': 'RD*'},
    {'Caravan': 'RD01*'},
    {'Detached': 'RD02*'},
    {'Semi-Detached': 'RD03*'},
    {'Terraced': 'RD04*'},
    {'Self Contained Flat (Includes Maisonette / Apartment)': 'RD06*'},
    {'House Boat': 'RD07*'},
    {'Sheltered Accommodation': 'RD08*'},
    {'Privately Owned Holiday Caravan / Chalet': 'RD10*'},
    {'Garage': 'RG*'},
    {'Lock-Up Garage / Garage Court': 'RG02*'},
    {'House In Multiple Occupation': 'RH*'},
    {'HMO Parent': 'RH01*'},
    {'HMO Bedsit / Other Non Self Contained Accommodation': 'RH02*'},
    {'HMO Not Further Divided': 'RH03*'},
    {'Residential Institution': 'RI*'},
    {'Care / Nursing Home': 'RI01*'},
    {'Communal Residence': 'RI02*'},
    {'Non-Commercial Lodgings': 'RI02NC*'},
    {'Religious Community': 'RI02RC*'},
    {'Residential Education': 'RI03*'},
    {'Unclassified': 'U*'},
    {'Awaiting Classification': 'UC*'},
    {'Pending Internal Investigation': 'UP*'},
    {'Dual Use': 'X*'},
    {'Object of Interest': 'Z*'},
    {'Archaeological Dig Site': 'ZA*'},
    {'Monument': 'ZM*'},
    {'Obelisk / Milestone / Standing Stone': 'ZM01*'},
    {'Obelisk': 'ZM01OB*'},
    {'Standing Stone': 'ZM01ST*'},
    {'Memorial / Market Cross': 'ZM02*'},
    {'Statue': 'ZM03*'},
    {'Castle / Historic Ruin': 'ZM04*'},
    {'Other Structure': 'ZM05*'},
    {'Boundary Stone': 'ZM05BS*'},
    {'Permanent Art Display / Sculpture': 'ZM05PN*'},
    {'Cascade / Fountain': 'ZM05CE*'},
    {'Windmill (Inactive)': 'ZM05WI*'},
    {'Stately Home': 'ZS*'},
    {'Underground Feature': 'ZU*'},
    {'Cave': 'ZU01*'},
    {'Pothole / Natural Hole': 'ZU04*'},
    {'Other Underground Feature': 'ZV*'},
    {'Cellar': 'ZV01*'},
    {'Disused Mine': 'ZV02*'},
    {'Mineral Mining / Inactive': 'ZV02MI*'},
    {'Oil And / Gas Extraction/ Inactive': 'ZV02OI*'},
    {'Mineral Quarrying And / Open Extraction / Inactive': 'ZV02QI*'},
    {'Well / Spring': 'ZV03*'},
    {'Spring': 'ZV03SG*'},
    {'Well': 'ZV03WL*'},
    {'Place Of Worship': 'ZW*'},
    {'Abbey': 'ZW99AB*'},
    {'Cathedral': 'ZW99CA*'},
    {'Church': 'ZW99CH*'},
    {'Chapel': 'ZW99CP*'},
    {'Gurdwara': 'ZW99GU*'},
    {'Kingdom Hall': 'ZW99KH*'},
    {'Mosque': 'ZW99MQ*'},
    {'Minster': 'ZW99MT*'},
    {'Stupa': 'ZW99SU*'},
    {'Synagogue': 'ZW99SY*'},
    {'Temple': 'ZW99TP*'},
    {'Lych Gate': 'ZW99LG*'},
    {'Residential Ancillary Building': 'RB*'},
    {'Land Ancillary Building': 'LB*'},
    {'Military Ancillary Building': 'MB*'},
    {'Commercial Ancillary Building': 'CB*'},
]


@pytest.mark.parametrize(
    'classification_string,classification_code',
    [
        (list(pair.keys())[0], list(pair.values())[0])
        for pair in classification_pairs
    ],
)
def test_check_reverse_classification(classification_string, classification_code):
    """ Check that the classification can be obtained from the string value """
    result = check_reverse_classification(classification_string)
    assert result == classification_code


