name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Name of the Docker image'
        required: true
        type: string
      image-tag:
        description: 'Version tag to assign to the Docker image. Leave empty to use version.txt.'
        required: false
        default: ''
        type: string

env:
  PROJECT_ID: 'ons-ci-aims'
  AR_REPO_LOCATION: 'europe-west2'
  AR_URL: 'europe-west2-docker.pkg.dev/ons-ci-aims/aims-ui-repository'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/709138365636/locations/global/workloadIdentityPools/github-actions-aims-pool/providers/aims-ui-provider'

permissions:
  contents: read
  id-token: write

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Read value from file
        id: read_file
        run: |
          VALUE=$(cat version.txt)
          echo "VALUE=$VALUE" >> "$GITHUB_ENV"

      - name: Use the value
        run: echo "The value is ${{ env.VALUE }}"

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.AR_REPO_LOCATION }}-docker.pkg.dev

      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ inputs.image-tag }}
        run: |
          if [ -z "$IMAGE_TAG" ]; then
            IMAGE_TAG="$VALUE"
          fi

          docker build \
            -t "${{ env.AR_URL }}/${{ inputs.image-name }}:${IMAGE_TAG}" \
            -t "${{ env.AR_URL }}/${{ inputs.image-name }}:latest" \
            .

      - name: Push Docker image
        run: |
          docker push "${{ env.AR_URL }}/${{ inputs.image-name }}" --all-tags