name: AIMS-DIY Version Check

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  compare-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aims-ui code
        uses: actions/checkout@v4

      - name: Checkout aims-diy repo
        uses: actions/checkout@v4
        with:
          repository: ONSdigital/aims-diy
          path: diy

      - name: Read versions and compare
        shell: bash
        run: |
          # read local version
          uiVersion=$(< version.txt)

          # extract remote version from docker-compose
          diyUiVersion=$(grep -A1 'address-index-ui:' diy/docker-compose.yml \
                   | grep image \
                   | sed -E 's/.*:([^"]+)".*/\1/')

          echo "The UI version is $uiVersion, the diy version of the UI is $diyUiVersion."

          # split versions for MAJOR.MINOR.PATCH
          IFS='.' read -r uiMajor uiMinor uiPatch <<< "$uiVersion"
          IFS='.' read -r diyMajor diyMinor diyPatch <<< "$diyUiVersion"

          # calculate diffs
          maj_diff=$((diyMajor - uiMajor))
          min_diff=$((diyMinor - uiMinor ))
          patch_diff=$((diyPatch - uiPatch))

          # Fail for a major version difference or a minor version difference greater than 20
          if (( maj_diff >= 1 )); then
            echo "::error::You are $maj_diff Major version(s) behind (local $uiVersionvs diy $diyUiVersion)."
            exit 1
          elif (( min_diff >= 1 )); then
            echo "::error::You are $min_diff Minor version(s) behind (local $uiVersionvs diy $diyUiVersion)."
            exit 1
          elif (( patch_diff > 25 )); then
            echo "::error::You are $patch_diff Patch version(s) behind (local $uiVersionvs diy $diyUiVersion)."
          else
            echo "You are up to date with the AIMS-DIY version, as it is not more than 25 PATCH versions behind, nor 1 MINOR versions, nor a MAJOR version."
            echo "The difference is Major: $maj_diff, Minor: $min_diff, Patch: $patch_diff."
          fi