name: AIMS-DIY Version Check

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  compare-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aims-ui code
        uses: actions/checkout@v4

      - name: Checkout aims-diy repo
        uses: actions/checkout@v4
        with:
          repository: ONSdigital/aims-diy
          path: diy

      - name: Read versions and compare
        shell: bash
        run: |
          # read local version
          uiVersion=$(< version.txt)

          # extract remote version from docker-compose
          diyUiVersion=$(grep -A1 'address-index-ui:' diy/docker-compose.yml \
                   | grep image \
                   | sed -E 's/.*:([^"]+)".*/\1/')


          # Split into semver parts
          IFS='.' read -r uiMajor uiMinor uiPatch <<< "$uiVersion"
          IFS='.' read -r diyMajor diyMinor diyPatch <<< "$diyUiVersion"

          # Difference calculations
          maj_diff=$(( uiMajor - diyMajor ))
          min_diff=$(( uiMinor - diyMinor ))
          patch_diff=$(( uiPatch - diyPatch ))

          echo "The UI version is $uiVersion, the diy version of the UI is $diyUiVersion. Consider upgrading."
          echo "Version Difference Breakdown: Major diff: $maj_diff (max 1), Minor diff: $min_diff (max 1), Patch diff: $patch_diff (max 25)."

          # Fail if ≥1 major version behind
          if (( maj_diff >= 1 )); then
            echo "::error::You are $maj_diff major version(s) behind (local $uiVersion vs diy $diyUiVersion)."
            exit 1

          # If same major but ≥1 minor behind
          elif (( maj_diff == 0 && min_diff >= 1 )); then
            echo "::error::You are $min_diff minor version(s) behind (local $uiVersion vs diy $diyUiVersion)."
            exit 1

          # If same major and minor but >25 patches behind
          elif (( maj_diff == 0 && min_diff == 0 && patch_diff > 25 )); then
            echo "::error::You are $patch_diff patch version(s) behind (local $uiVersion vs diy $diyUiVersion)."
            exit 1

          fi