name: AIMS-DIY Version Check

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  compare-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aims-ui code
        uses: actions/checkout@v4

      - name: Checkout aims-diy repo
        uses: actions/checkout@v4
        with:
          repository: ONSdigital/aims-diy
          path: diy

      - id: compare
        name: Read versions and compare
        shell: bash
        run: |
          # read local version
          uiVersion=$(< version.txt)

          # extract remote version from docker-compose
          diyUiVersion=$(grep -A1 'address-index-ui:' diy/docker-compose.yml \
                   | grep image \
                   | sed -E 's/.*:([^"]+)".*/\1/')


          # Split into semver parts
          IFS='.' read -r uiMajor uiMinor uiPatch <<< "$uiVersion"
          IFS='.' read -r diyMajor diyMinor diyPatch <<< "$diyUiVersion"

          # Difference calculations
          maj_diff=$(( uiMajor - diyMajor ))
          min_diff=$(( uiMinor - diyMinor ))
          patch_diff=$(( uiPatch - diyPatch ))

          echo "The UI version is $uiVersion, the diy version of the UI is $diyUiVersion. Consider upgrading the AIMS-DIY Repository with the latest UI image."
          echo "Version Difference Breakdown: Major diff: $maj_diff (max 1), Minor diff: $min_diff (max 1), Patch diff: $patch_diff (max 25)."

          # Fail if ≥1 major version behind
          if (( maj_diff >= 1 )); then
            echo "::warning::You are $maj_diff major version(s) behind (local $uiVersion vs diy $diyUiVersion)."

          # If same major but ≥1 minor behind
          elif (( maj_diff == 0 && min_diff >= 1 )); then
            echo "::warning::You are $min_diff minor version(s) behind (local $uiVersion vs diy $diyUiVersion)."

          # If same major and minor but >25 patches behind
          elif (( maj_diff == 0 && min_diff == 0 && patch_diff > 25 )); then
            echo "::warning::You are $patch_diff patch version(s) behind (local $uiVersion vs diy $diyUiVersion)."
          fi

          # write a "behind" flag if ANY of our thresholds tripped
          if (( maj_diff >= 1 )) || 
             (( maj_diff == 0 && min_diff >= 1 )) || 
             (( maj_diff == 0 && min_diff == 0 && patch_diff > 25 )); then
            echo "behind=true" >> $GITHUB_OUTPUT
          else
            echo "behind=false" >> $GITHUB_OUTPUT
          fi
        
          # Export outputs for the next step
          behind=false
          if (( maj_diff >= 1 )) || \
             (( maj_diff == 0 && min_diff >= 1 )) || \
             (( maj_diff == 0 && min_diff == 0 && patch_diff > 25 )); then
            behind=true
          fi

          echo "behind=$behind"        >> $GITHUB_OUTPUT
          echo "uiVersion=$uiVersion"  >> $GITHUB_OUTPUT
          echo "diyVersion=$diyUiVersion" >> $GITHUB_OUTPUT


      - name: Report as a check run
        if: steps.compare.outputs.behind == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const sha           = context.sha;
            const uiVersion     = '${{ steps.compare.outputs.uiVersion }}';
            const diyVersion    = '${{ steps.compare.outputs.diyVersion }}';

            await github.rest.checks.create({
              owner,
              repo,
              sha,
              name: 'AIMS-DIY Version',
              status: 'completed',
              conclusion: 'failure',
              output: {
                title: `UI ${uiVersion} behind diy ${diyVersion}`,
                summary: `Consider upgrading the AIMS-DIY repo with the latest UI image.`
              }
            });