name: Create a UI test image for AP

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to assign to the Docker image'
        required: true
        default: '0.0.1'
env:
  IMAGE_NAME: 'address-index-ui-test'
  PROJECT_ID: 'ons-ci-aims'
  AR_REPO_LOCATION: 'europe-west2'
  AR_URL: 'europe-west2-docker.pkg.dev/ons-ci-aims/aims-ui-repository'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/709138365636/locations/global/workloadIdentityPools/github-actions-aims-pool/providers/aims-ui-provider'
permissions:
  contents: read
  id-token: write
jobs:
  test-js-unit-tests:
      name: Run JavaScript unit tests
      if: github.ref != 'refs/heads/main'
      uses: ./.github/workflows/test-js-jest-unit-tests.yml

  test-python-playwright-against-api-demo:
    name: Run Python Playwright tests against API Demo
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/test-python-playwright-against-api-demo.yml

  test-python-unit-tests:
    name: Run Python unit tests
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/test-python-unit-tests.yml

  push-image:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - test-js-unit-tests
      - test-python-playwright-against-api-demo
      - test-python-unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Read value from file
        id: read_file
        run: |
          VALUE=$(cat version.txt)
          echo "VALUE=$VALUE" >> $GITHUB_ENV

      - name: Use the value
        run: echo "The value is ${{ env.VALUE }}"

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.AR_REPO_LOCATION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}" -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:latest" .

      - name: Push Docker image
        run: |
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}" --all-tags
