name: Python and JavaScript application

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Clone the API repository
    - name: Clone API repository
      run: git clone https://github.com/ONSdigital/address-index-api.git api_service

    # Set up Docker Compose and start the API service
    - name: Start API with Docker Compose
      run: |
        cd api_service
        docker-compose up -d
        docker ps -a  # Show running containers for debugging

    # Wait for API to be ready (checking port 9001)
    - name: Wait for API to be ready
      run: |
        timeout 60s bash -c 'until curl -s http://localhost:9001/healthcheck; do sleep 5; done'

    # Set up Python environment and run Python tests
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Python package
      run: |
        pip install -e .

    - name: Install Playwright Browsers
      run: |
        python3 -m playwright install --with-deps

    - name: Run Python tests
      run: |
        python3 -m pytest tests/pytest_tests -n 8

    # Set up Node.js environment and run JavaScript tests
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Replace with the Node.js version you need

    - name: Install npm dependencies
      run: npm install

    - name: Run JavaScript tests
      run: npm run test:jest

    # Stop Docker Compose and clean up
    - name: Stop and clean up Docker containers
      if: always()
      run: |
        cd api_service
        docker-compose down

